dependencies:
  - name: helm-apps
    version: ~1
    repository: "https://flant.github.io/helm-apps"
  - name: postgresql
    version: ^13.2.25
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: ^18.6.1
    repository: https://charts.bitnami.com/bitnami