name: Deploy to dev
on:
  push:
    branches:
      - "main"
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: dev
          kube-config-base64-data: ${{ secrets.WERF_KUBECONFIG_BASE64 }}
        env:
          WERF_NAMESPACE: dataton-mipt
